dnu wrap Framework\Thriot.Framework\Thriot.Framework.csproj
dnu wrap Framework\Thriot.Framework.Azure\Thriot.Framework.Azure.csproj
dnu wrap Framework\Thriot.Framework.Mails\Thriot.Framework.Mails.csproj
dnu wrap Framework\Thriot.Framework.Sql\Thriot.Framework.Sql.csproj
dnu wrap Management\Thriot.Management.Model\Thriot.Management.Model.csproj
dnu wrap Management\Thriot.Management.Operations.Azure\Thriot.Management.Operations.Azure.csproj
dnu wrap Management\Thriot.Management.Operations.Sql\Thriot.Management.Operations.Sql.csproj
dnu wrap Management\Thriot.Management.Services\Thriot.Management.Services.csproj
dnu wrap Messaging\Thriot.Messaging.Services\Thriot.Messaging.Services.csproj
dnu wrap Messaging\Thriot.Messaging.Services.Client\Thriot.Messaging.Services.Client.csproj
dnu wrap Objects\Thriot.Objects.Common\Thriot.Objects.Common.csproj
dnu wrap Objects\Thriot.Objects.Model\Thriot.Objects.Model.csproj
dnu wrap Objects\Thriot.Objects.Operations.Azure\Thriot.Objects.Operations.Azure.csproj
dnu wrap Objects\Thriot.Objects.Operations.Sql\Thriot.Objects.Operations.Sql.csproj
dnu wrap Platform\Thriot.Platform.Model\Thriot.Platform.Model.csproj
dnu wrap Platform\Thriot.Platform.Services.Client\Thriot.Platform.Services.Client.csproj
dnu wrap Platform\Thriot.Platform.Services.Messaging\Thriot.Platform.Services.Messaging.csproj
dnu wrap Platform\Thriot.Platform.Services.Telemetry\Thriot.Platform.Services.Telemetry.csproj
dnu wrap Plugins\Thriot.Plugins.Core\Thriot.Plugins.Core.csproj
dnu wrap Reporting\Thriot.Reporting.Services\Thriot.Reporting.Services.csproj
